# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import safeguard_upload_pb2 as safeguard__upload__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in safeguard_upload_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UploadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitUpload = channel.unary_unary(
                '/safeguard.upload.v1.UploadService/InitUpload',
                request_serializer=safeguard__upload__pb2.InitUploadRequest.SerializeToString,
                response_deserializer=safeguard__upload__pb2.InitUploadResponse.FromString,
                _registered_method=True)
        self.UploadChunks = channel.stream_unary(
                '/safeguard.upload.v1.UploadService/UploadChunks',
                request_serializer=safeguard__upload__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=safeguard__upload__pb2.UploadChunksResponse.FromString,
                _registered_method=True)
        self.GetUploadStatus = channel.unary_unary(
                '/safeguard.upload.v1.UploadService/GetUploadStatus',
                request_serializer=safeguard__upload__pb2.UploadStatusRequest.SerializeToString,
                response_deserializer=safeguard__upload__pb2.UploadStatusResponse.FromString,
                _registered_method=True)
        self.CompleteUpload = channel.unary_unary(
                '/safeguard.upload.v1.UploadService/CompleteUpload',
                request_serializer=safeguard__upload__pb2.CompleteUploadRequest.SerializeToString,
                response_deserializer=safeguard__upload__pb2.CompleteUploadResponse.FromString,
                _registered_method=True)


class UploadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.InitUpload,
                    request_deserializer=safeguard__upload__pb2.InitUploadRequest.FromString,
                    response_serializer=safeguard__upload__pb2.InitUploadResponse.SerializeToString,
            ),
            'UploadChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadChunks,
                    request_deserializer=safeguard__upload__pb2.UploadChunkRequest.FromString,
                    response_serializer=safeguard__upload__pb2.UploadChunksResponse.SerializeToString,
            ),
            'GetUploadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadStatus,
                    request_deserializer=safeguard__upload__pb2.UploadStatusRequest.FromString,
                    response_serializer=safeguard__upload__pb2.UploadStatusResponse.SerializeToString,
            ),
            'CompleteUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteUpload,
                    request_deserializer=safeguard__upload__pb2.CompleteUploadRequest.FromString,
                    response_serializer=safeguard__upload__pb2.CompleteUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'safeguard.upload.v1.UploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('safeguard.upload.v1.UploadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UploadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/safeguard.upload.v1.UploadService/InitUpload',
            safeguard__upload__pb2.InitUploadRequest.SerializeToString,
            safeguard__upload__pb2.InitUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/safeguard.upload.v1.UploadService/UploadChunks',
            safeguard__upload__pb2.UploadChunkRequest.SerializeToString,
            safeguard__upload__pb2.UploadChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUploadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/safeguard.upload.v1.UploadService/GetUploadStatus',
            safeguard__upload__pb2.UploadStatusRequest.SerializeToString,
            safeguard__upload__pb2.UploadStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/safeguard.upload.v1.UploadService/CompleteUpload',
            safeguard__upload__pb2.CompleteUploadRequest.SerializeToString,
            safeguard__upload__pb2.CompleteUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
